# Generated by Django 5.0.6 on 2024-05-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_properties_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
    ]
